name: release # 任务名称

on: # 触发条件
  push: # 在push时触发
    tags: # 标签  这里标识在push tag时触发
      - 'v*' # 以v开头的版本

jobs: # 任务
  build: # 任务ID
    runs-on: windows-latest # 运行环境 此处为windows环境，可根据实际情况选择
    steps:
    - name: Upload # 上传
      uses: softprops/action-gh-release@v2 # 使用第三方actions 上传
      if: startsWith(github.ref, 'refs/tags/') # 仅在tag时上传
      with:
        文件: dist/env-manage.7z # 上传的文件
